version: '3.8'

services:
  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000
    environment: 
      - MONGO_URL=mongodb://localhost:27017
      - MONGO_TABLE=bugme
      - secret=rJecfSGLVm890yWs2OGFNVGphnz7lTMuvSXQE12TwWHnSPG
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bugme.rule=Host(`bugme.localhost`)"
  traefik:
    image: traefik:v2.2
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"